In [1]:
import os
import pandas as pd
from metrics import TaskTime, TaskTimeDeviation, create_report

# Пример использования функции для создания отчетов
Следуюие 2 ячейки делают одно и то же, но одна из них собирает все таблицы в словарь **data_tabels**

In [2]:
dir = os.path.join('courses', 'machine_learning')
data_tables = {file[:-4] : pd.read_csv(os.path.join(dir, file)) for file
               in os.listdir(dir)
              }

In [3]:
dir = os.path.join('courses', 'machine_learning')
files = ['']
course = pd.read_csv(os.path.join(dir, 'course.csv'))
course_module = pd.read_csv(os.path.join(dir, 'course_module.csv'))
course_element = pd.read_csv(os.path.join(dir, 'course_element.csv'))
user_course_progress = pd.read_csv(os.path.join(dir, 'user_course_progress.csv'))
user_module_progress = pd.read_csv(os.path.join(dir, 'user_module_progress.csv'))
user_element_progress = pd.read_csv(os.path.join(dir, 'user_element_progress.csv'))
solution_log = pd.read_csv(os.path.join(dir, 'solution_log.csv'))

Создаем метрики, которые хотим посчитать и объединяем их в **metrics_list**:

In [4]:
median_time = TaskTime(metric_name='median_time', data_tables=data_tables, parameters={'metric' : 'median'}, threshold=1)
mean_time = TaskTime(metric_name='mean_time', data_tables=data_tables, parameters={'metric' : 'mean'}, threshold=7.5)
median_dev = TaskTimeDeviation(metric_name='median_dev', data_tables=data_tables, parameters={'metric' : 'median'}, threshold=1)
mean_dev = TaskTimeDeviation(metric_name='mean_dev', data_tables=data_tables, parameters={'metric' : 'mean'}, threshold=7.5)
metrics_list = [median_time, mean_time, median_dev, mean_dev]

Считаем все метрики вместе, сохраняем результат в файлы, сохранять в переменную не обязательно:

In [5]:
styled_tables = create_report(course_id=1555, metrics_list=metrics_list, data_tables=data_tables)

Каждый файл содержит вычисленные метрики для каждого модуля в выбранном запуске курса. Таблицы отформатированы следующим образом: *красным* подсвечены ячейки, значение в которых выше порога, *зеленым* те, в которых ниже. Пример того, как выглядит таблица:

In [6]:
styled_tables[0]